// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkDuplicateDevice = `-- name: CheckDuplicateDevice :one
SELECT id, session_id, user_id, marked_at, method, latitude, longitude, distance_from_center, mock_location_detected, confidence_score, week_number, device_id, device_model, os_version FROM attendance_records
WHERE session_id = $1 AND device_id = $2
LIMIT 1
`

type CheckDuplicateDeviceParams struct {
	SessionID pgtype.UUID
	DeviceID  pgtype.Text
}

func (q *Queries) CheckDuplicateDevice(ctx context.Context, arg CheckDuplicateDeviceParams) (AttendanceRecord, error) {
	row := q.db.QueryRow(ctx, checkDuplicateDevice, arg.SessionID, arg.DeviceID)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.MarkedAt,
		&i.Method,
		&i.Latitude,
		&i.Longitude,
		&i.DistanceFromCenter,
		&i.MockLocationDetected,
		&i.ConfidenceScore,
		&i.WeekNumber,
		&i.DeviceID,
		&i.DeviceModel,
		&i.OsVersion,
	)
	return i, err
}

const createAttendanceRecord = `-- name: CreateAttendanceRecord :one
INSERT INTO attendance_records (
    session_id,
    user_id,
    method,
    latitude,
    longitude,
    distance_from_center,
    mock_location_detected,
    confidence_score,
    week_number,
    device_id,
    device_model,
    os_version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, session_id, user_id, marked_at, method, latitude, longitude, distance_from_center, mock_location_detected, confidence_score, week_number, device_id, device_model, os_version
`

type CreateAttendanceRecordParams struct {
	SessionID            pgtype.UUID
	UserID               pgtype.UUID
	Method               string
	Latitude             float64
	Longitude            float64
	DistanceFromCenter   float64
	MockLocationDetected bool
	ConfidenceScore      float64
	WeekNumber           int32
	DeviceID             pgtype.Text
	DeviceModel          pgtype.Text
	OsVersion            pgtype.Text
}

func (q *Queries) CreateAttendanceRecord(ctx context.Context, arg CreateAttendanceRecordParams) (AttendanceRecord, error) {
	row := q.db.QueryRow(ctx, createAttendanceRecord,
		arg.SessionID,
		arg.UserID,
		arg.Method,
		arg.Latitude,
		arg.Longitude,
		arg.DistanceFromCenter,
		arg.MockLocationDetected,
		arg.ConfidenceScore,
		arg.WeekNumber,
		arg.DeviceID,
		arg.DeviceModel,
		arg.OsVersion,
	)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.MarkedAt,
		&i.Method,
		&i.Latitude,
		&i.Longitude,
		&i.DistanceFromCenter,
		&i.MockLocationDetected,
		&i.ConfidenceScore,
		&i.WeekNumber,
		&i.DeviceID,
		&i.DeviceModel,
		&i.OsVersion,
	)
	return i, err
}

const getAttendanceByCourse = `-- name: GetAttendanceByCourse :many
SELECT
    ar.id,
    ar.session_id,
    ar.user_id,
    ar.marked_at,
    ar.method,
    ar.latitude,
    ar.longitude,
    ar.distance_from_center,
    ar.mock_location_detected,
    ar.confidence_score,
    ar.week_number,
    ar.device_id,
    ar.device_model,
    ar.os_version,
    u.first_name,
    u.last_name,
    cm.matriculation_number,
    u.department
FROM attendance_records ar
JOIN users u ON ar.user_id = u.id
JOIN course_members cm ON cm.user_id = ar.user_id AND cm.course_id = $1
WHERE ar.session_id IN (
    SELECT id FROM sessions WHERE course_id = $1
)
ORDER BY u.last_name ASC, ar.week_number ASC
`

type GetAttendanceByCourseRow struct {
	ID                   pgtype.UUID
	SessionID            pgtype.UUID
	UserID               pgtype.UUID
	MarkedAt             pgtype.Timestamptz
	Method               string
	Latitude             float64
	Longitude            float64
	DistanceFromCenter   float64
	MockLocationDetected bool
	ConfidenceScore      float64
	WeekNumber           int32
	DeviceID             pgtype.Text
	DeviceModel          pgtype.Text
	OsVersion            pgtype.Text
	FirstName            string
	LastName             string
	MatriculationNumber  pgtype.Text
	Department           pgtype.Text
}

func (q *Queries) GetAttendanceByCourse(ctx context.Context, courseID pgtype.UUID) ([]GetAttendanceByCourseRow, error) {
	rows, err := q.db.Query(ctx, getAttendanceByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttendanceByCourseRow
	for rows.Next() {
		var i GetAttendanceByCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.MarkedAt,
			&i.Method,
			&i.Latitude,
			&i.Longitude,
			&i.DistanceFromCenter,
			&i.MockLocationDetected,
			&i.ConfidenceScore,
			&i.WeekNumber,
			&i.DeviceID,
			&i.DeviceModel,
			&i.OsVersion,
			&i.FirstName,
			&i.LastName,
			&i.MatriculationNumber,
			&i.Department,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttendanceBySession = `-- name: GetAttendanceBySession :many
SELECT
    ar.id,
    ar.session_id,
    ar.user_id,
    ar.marked_at,
    ar.method,
    ar.latitude,
    ar.longitude,
    ar.distance_from_center,
    ar.mock_location_detected,
    ar.confidence_score,
    ar.week_number,
    ar.device_id,
    ar.device_model,
    ar.os_version,
    u.first_name,
    u.last_name,
    cm.matriculation_number,
    u.department
FROM attendance_records ar
JOIN users u ON ar.user_id = u.id
JOIN sessions s ON ar.session_id = s.id
JOIN course_members cm ON cm.user_id = ar.user_id AND cm.course_id = s.course_id
WHERE ar.session_id = $1
ORDER BY ar.marked_at ASC
`

type GetAttendanceBySessionRow struct {
	ID                   pgtype.UUID
	SessionID            pgtype.UUID
	UserID               pgtype.UUID
	MarkedAt             pgtype.Timestamptz
	Method               string
	Latitude             float64
	Longitude            float64
	DistanceFromCenter   float64
	MockLocationDetected bool
	ConfidenceScore      float64
	WeekNumber           int32
	DeviceID             pgtype.Text
	DeviceModel          pgtype.Text
	OsVersion            pgtype.Text
	FirstName            string
	LastName             string
	MatriculationNumber  pgtype.Text
	Department           pgtype.Text
}

func (q *Queries) GetAttendanceBySession(ctx context.Context, sessionID pgtype.UUID) ([]GetAttendanceBySessionRow, error) {
	rows, err := q.db.Query(ctx, getAttendanceBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttendanceBySessionRow
	for rows.Next() {
		var i GetAttendanceBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.MarkedAt,
			&i.Method,
			&i.Latitude,
			&i.Longitude,
			&i.DistanceFromCenter,
			&i.MockLocationDetected,
			&i.ConfidenceScore,
			&i.WeekNumber,
			&i.DeviceID,
			&i.DeviceModel,
			&i.OsVersion,
			&i.FirstName,
			&i.LastName,
			&i.MatriculationNumber,
			&i.Department,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttendanceByUserAndSession = `-- name: GetAttendanceByUserAndSession :one
SELECT id, session_id, user_id, marked_at, method, latitude, longitude, distance_from_center, mock_location_detected, confidence_score, week_number, device_id, device_model, os_version FROM attendance_records
WHERE user_id = $1 AND session_id = $2
`

type GetAttendanceByUserAndSessionParams struct {
	UserID    pgtype.UUID
	SessionID pgtype.UUID
}

func (q *Queries) GetAttendanceByUserAndSession(ctx context.Context, arg GetAttendanceByUserAndSessionParams) (AttendanceRecord, error) {
	row := q.db.QueryRow(ctx, getAttendanceByUserAndSession, arg.UserID, arg.SessionID)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.MarkedAt,
		&i.Method,
		&i.Latitude,
		&i.Longitude,
		&i.DistanceFromCenter,
		&i.MockLocationDetected,
		&i.ConfidenceScore,
		&i.WeekNumber,
		&i.DeviceID,
		&i.DeviceModel,
		&i.OsVersion,
	)
	return i, err
}
