// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (
    owner_id,
    title,
    code,
    department,
    invite_code
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, owner_id, title, code, department, created_at, invite_code
`

type CreateCourseParams struct {
	OwnerID    pgtype.UUID
	Title      string
	Code       string
	Department pgtype.Text
	InviteCode string
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.OwnerID,
		arg.Title,
		arg.Code,
		arg.Department,
		arg.InviteCode,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Code,
		&i.Department,
		&i.CreatedAt,
		&i.InviteCode,
	)
	return i, err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses
WHERE id = $1
`

func (q *Queries) DeleteCourse(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCourse, id)
	return err
}

const getCourseByCode = `-- name: GetCourseByCode :one
SELECT id, owner_id, title, code, department, created_at, invite_code FROM courses
WHERE code = $1
`

func (q *Queries) GetCourseByCode(ctx context.Context, code string) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByCode, code)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Code,
		&i.Department,
		&i.CreatedAt,
		&i.InviteCode,
	)
	return i, err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, owner_id, title, code, department, created_at, invite_code FROM courses
WHERE id = $1
`

func (q *Queries) GetCourseByID(ctx context.Context, id pgtype.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Code,
		&i.Department,
		&i.CreatedAt,
		&i.InviteCode,
	)
	return i, err
}

const getCourseByInviteCode = `-- name: GetCourseByInviteCode :one
SELECT id, owner_id, title, code, department, created_at, invite_code FROM courses
WHERE invite_code = $1
`

func (q *Queries) GetCourseByInviteCode(ctx context.Context, inviteCode string) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByInviteCode, inviteCode)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Code,
		&i.Department,
		&i.CreatedAt,
		&i.InviteCode,
	)
	return i, err
}

const getCoursesByOwner = `-- name: GetCoursesByOwner :many
SELECT id, owner_id, title, code, department, created_at, invite_code FROM courses
WHERE owner_id = $1
`

func (q *Queries) GetCoursesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Course, error) {
	rows, err := q.db.Query(ctx, getCoursesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Code,
			&i.Department,
			&i.CreatedAt,
			&i.InviteCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
