// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: course_members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCourseMember = `-- name: AddCourseMember :one
INSERT INTO course_members (
    course_id,
    user_id,
    role
) VALUES (
    $1, $2, $3
)
RETURNING id, course_id, user_id, role, joined_at
`

type AddCourseMemberParams struct {
	CourseID pgtype.UUID
	UserID   pgtype.UUID
	Role     string
}

func (q *Queries) AddCourseMember(ctx context.Context, arg AddCourseMemberParams) (CourseMember, error) {
	row := q.db.QueryRow(ctx, addCourseMember, arg.CourseID, arg.UserID, arg.Role)
	var i CourseMember
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getCourseMember = `-- name: GetCourseMember :one
SELECT id, course_id, user_id, role, joined_at FROM course_members
WHERE course_id = $1 AND user_id = $2
`

type GetCourseMemberParams struct {
	CourseID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) GetCourseMember(ctx context.Context, arg GetCourseMemberParams) (CourseMember, error) {
	row := q.db.QueryRow(ctx, getCourseMember, arg.CourseID, arg.UserID)
	var i CourseMember
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getCourseMembersByCourse = `-- name: GetCourseMembersByCourse :many
SELECT id, course_id, user_id, role, joined_at FROM course_members
WHERE course_id = $1
`

func (q *Queries) GetCourseMembersByCourse(ctx context.Context, courseID pgtype.UUID) ([]CourseMember, error) {
	rows, err := q.db.Query(ctx, getCourseMembersByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseMember
	for rows.Next() {
		var i CourseMember
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursesByMember = `-- name: GetCoursesByMember :many
SELECT id, course_id, user_id, role, joined_at FROM course_members
WHERE user_id = $1
`

func (q *Queries) GetCoursesByMember(ctx context.Context, userID pgtype.UUID) ([]CourseMember, error) {
	rows, err := q.db.Query(ctx, getCoursesByMember, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseMember
	for rows.Next() {
		var i CourseMember
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
