// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: course_members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCourseMember = `-- name: AddCourseMember :one
INSERT INTO course_members (
    course_id,
    user_id,
    role,
    co_lecturer
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, course_id, user_id, role, joined_at, co_lecturer
`

type AddCourseMemberParams struct {
	CourseID   pgtype.UUID
	UserID     pgtype.UUID
	Role       string
	CoLecturer bool
}

func (q *Queries) AddCourseMember(ctx context.Context, arg AddCourseMemberParams) (CourseMember, error) {
	row := q.db.QueryRow(ctx, addCourseMember,
		arg.CourseID,
		arg.UserID,
		arg.Role,
		arg.CoLecturer,
	)
	var i CourseMember
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.CoLecturer,
	)
	return i, err
}

const getCourseMember = `-- name: GetCourseMember :one
SELECT id, course_id, user_id, role, joined_at, co_lecturer FROM course_members
WHERE course_id = $1 AND user_id = $2
`

type GetCourseMemberParams struct {
	CourseID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) GetCourseMember(ctx context.Context, arg GetCourseMemberParams) (CourseMember, error) {
	row := q.db.QueryRow(ctx, getCourseMember, arg.CourseID, arg.UserID)
	var i CourseMember
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.CoLecturer,
	)
	return i, err
}

const getCourseMembersByCourse = `-- name: GetCourseMembersByCourse :many
SELECT 
    cm.course_id,
    cm.user_id,
    cm.role,
    cm.co_lecturer,
    cm.joined_at,
    u.first_name,
    u.last_name,
    u.email,
    u.avatar_url,
    u.department,
    u.matric_number
FROM course_members cm
JOIN users u ON cm.user_id = u.id
WHERE cm.course_id = $1
ORDER BY u.first_name ASC, u.last_name ASC
`

type GetCourseMembersByCourseRow struct {
	CourseID     pgtype.UUID
	UserID       pgtype.UUID
	Role         string
	CoLecturer   bool
	JoinedAt     pgtype.Timestamptz
	FirstName    string
	LastName     string
	Email        string
	AvatarUrl    pgtype.Text
	Department   string
	MatricNumber pgtype.Text
}

func (q *Queries) GetCourseMembersByCourse(ctx context.Context, courseID pgtype.UUID) ([]GetCourseMembersByCourseRow, error) {
	rows, err := q.db.Query(ctx, getCourseMembersByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCourseMembersByCourseRow
	for rows.Next() {
		var i GetCourseMembersByCourseRow
		if err := rows.Scan(
			&i.CourseID,
			&i.UserID,
			&i.Role,
			&i.CoLecturer,
			&i.JoinedAt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.AvatarUrl,
			&i.Department,
			&i.MatricNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCourseMember = `-- name: RemoveCourseMember :exec
DELETE FROM course_members
WHERE course_id = $1 AND user_id = $2
`

type RemoveCourseMemberParams struct {
	CourseID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) RemoveCourseMember(ctx context.Context, arg RemoveCourseMemberParams) error {
	_, err := q.db.Exec(ctx, removeCourseMember, arg.CourseID, arg.UserID)
	return err
}
