// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type UserRole string

const (
	UserRoleStudent  UserRole = "student"
	UserRoleLecturer UserRole = "lecturer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AttendanceRecord struct {
	ID                   pgtype.UUID
	SessionID            pgtype.UUID
	UserID               pgtype.UUID
	MarkedAt             pgtype.Timestamptz
	Method               string
	Latitude             float64
	Longitude            float64
	DistanceFromCenter   float64
	MockLocationDetected bool
	ConfidenceScore      float64
	WeekNumber           int32
	DeviceID             pgtype.Text
	DeviceModel          pgtype.Text
	OsVersion            pgtype.Text
}

type Course struct {
	ID                  pgtype.UUID
	OwnerID             pgtype.UUID
	Title               string
	Code                string
	Department          pgtype.Text
	CreatedAt           pgtype.Timestamptz
	InviteCode          string
	ConfidenceThreshold pgtype.Numeric
}

type CourseMember struct {
	ID                  pgtype.UUID
	CourseID            pgtype.UUID
	UserID              pgtype.UUID
	Role                string
	MatriculationNumber pgtype.Text
	JoinedAt            pgtype.Timestamptz
	CoLecturer          bool
}

type OtpCode struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
	UserID    pgtype.UUID
	Code      string
	IssuedAt  pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	Used      bool
}

type QrToken struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
	Token     string
	IssuedAt  pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	Used      bool
}

type Session struct {
	ID             pgtype.UUID
	CourseID       pgtype.UUID
	CreatedBy      pgtype.UUID
	Title          pgtype.Text
	WeekNumber     int32
	Latitude       float64
	Longitude      float64
	RadiusMeters   float64
	QrRotationSecs int32
	Status         string
	StartedAt      pgtype.Timestamptz
	ClosedAt       pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	FirstName    string
	LastName     string
	CreatedAt    pgtype.Timestamptz
	GoogleID     pgtype.Text
	AvatarUrl    pgtype.Text
	Role         UserRole
	PasswordHash pgtype.Text
}
