// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AttendanceRecord struct {
	ID                   pgtype.UUID
	SessionID            pgtype.UUID
	UserID               pgtype.UUID
	MarkedAt             pgtype.Timestamptz
	Method               string
	Latitude             float64
	Longitude            float64
	DistanceFromCenter   float64
	MockLocationDetected bool
	ConfidenceScore      float64
	WeekNumber           int32
}

type Course struct {
	ID         pgtype.UUID
	OwnerID    pgtype.UUID
	Title      string
	Code       string
	Department pgtype.Text
	CreatedAt  pgtype.Timestamptz
	InviteCode string
}

type CourseMember struct {
	ID       pgtype.UUID
	CourseID pgtype.UUID
	UserID   pgtype.UUID
	Role     string
	JoinedAt pgtype.Timestamptz
}

type OtpCode struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
	UserID    pgtype.UUID
	Code      string
	IssuedAt  pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	Used      bool
}

type QrToken struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
	Token     string
	IssuedAt  pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	Used      bool
}

type Session struct {
	ID             pgtype.UUID
	CourseID       pgtype.UUID
	CreatedBy      pgtype.UUID
	Title          pgtype.Text
	WeekNumber     int32
	Latitude       float64
	Longitude      float64
	RadiusMeters   float64
	QrRotationSecs int32
	Status         string
	StartedAt      pgtype.Timestamptz
	ClosedAt       pgtype.Timestamptz
}

type User struct {
	ID                  pgtype.UUID
	Email               string
	PasswordHash        string
	FirstName           string
	LastName            string
	MatriculationNumber string
	Department          pgtype.Text
	CreatedAt           pgtype.Timestamptz
}
