// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, course_id, type, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, course_id, type, payload, seen_at, created_at
`

type CreateNotificationParams struct {
	UserID   pgtype.UUID
	CourseID pgtype.UUID
	Type     string
	Payload  []byte
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.CourseID,
		arg.Type,
		arg.Payload,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.Type,
		&i.Payload,
		&i.SeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const createNotificationsForCourseMembers = `-- name: CreateNotificationsForCourseMembers :exec
INSERT INTO notifications (user_id, course_id, type, payload)
SELECT user_id, $1, $2, $3
FROM course_members
WHERE course_id = $1
`

type CreateNotificationsForCourseMembersParams struct {
	CourseID pgtype.UUID
	Type     string
	Payload  []byte
}

func (q *Queries) CreateNotificationsForCourseMembers(ctx context.Context, arg CreateNotificationsForCourseMembersParams) error {
	_, err := q.db.Exec(ctx, createNotificationsForCourseMembers, arg.CourseID, arg.Type, arg.Payload)
	return err
}

const getUnseenNotificationsByUser = `-- name: GetUnseenNotificationsByUser :many
SELECT id, user_id, course_id, type, payload, seen_at, created_at FROM notifications
WHERE user_id = $1 AND seen_at IS NULL AND created_at >= $2
ORDER BY created_at DESC
LIMIT 50
`

type GetUnseenNotificationsByUserParams struct {
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetUnseenNotificationsByUser(ctx context.Context, arg GetUnseenNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getUnseenNotificationsByUser, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CourseID,
			&i.Type,
			&i.Payload,
			&i.SeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationAsSeen = `-- name: MarkNotificationAsSeen :exec
UPDATE notifications
SET seen_at = NOW()
WHERE id = $1 AND user_id = $2
`

type MarkNotificationAsSeenParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) MarkNotificationAsSeen(ctx context.Context, arg MarkNotificationAsSeenParams) error {
	_, err := q.db.Exec(ctx, markNotificationAsSeen, arg.ID, arg.UserID)
	return err
}
