// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otp.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOTP = `-- name: CreateOTP :one
INSERT INTO otp_codes (
    session_id,
    user_id,
    code,
    expires_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, session_id, user_id, code, issued_at, expires_at, used
`

type CreateOTPParams struct {
	SessionID pgtype.UUID
	UserID    pgtype.UUID
	Code      string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOTP,
		arg.SessionID,
		arg.UserID,
		arg.Code,
		arg.ExpiresAt,
	)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Code,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const getValidOTP = `-- name: GetValidOTP :one
SELECT id, session_id, user_id, code, issued_at, expires_at, used FROM otp_codes
WHERE user_id = $1 
  AND session_id = $2 
  AND code = $3 
  AND used = false 
  AND expires_at > NOW()
`

type GetValidOTPParams struct {
	UserID    pgtype.UUID
	SessionID pgtype.UUID
	Code      string
}

func (q *Queries) GetValidOTP(ctx context.Context, arg GetValidOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getValidOTP, arg.UserID, arg.SessionID, arg.Code)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Code,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const markOTPUsed = `-- name: MarkOTPUsed :exec
UPDATE otp_codes 
SET used = true 
WHERE id = $1
`

func (q *Queries) MarkOTPUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOTPUsed, id)
	return err
}
