// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: qr_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQRToken = `-- name: CreateQRToken :one
INSERT INTO qr_tokens (
    session_id,
    token,
    expires_at
) VALUES (
    $1, $2, $3
)
RETURNING id, session_id, token, issued_at, expires_at, used
`

type CreateQRTokenParams struct {
	SessionID pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateQRToken(ctx context.Context, arg CreateQRTokenParams) (QrToken, error) {
	row := q.db.QueryRow(ctx, createQRToken, arg.SessionID, arg.Token, arg.ExpiresAt)
	var i QrToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Token,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const getValidQRToken = `-- name: GetValidQRToken :one
SELECT id, session_id, token, issued_at, expires_at, used FROM qr_tokens
WHERE token = $1
AND used = false
AND expires_at > NOW()
`

func (q *Queries) GetValidQRToken(ctx context.Context, token string) (QrToken, error) {
	row := q.db.QueryRow(ctx, getValidQRToken, token)
	var i QrToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Token,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const invalidatePreviousTokens = `-- name: InvalidatePreviousTokens :exec
UPDATE qr_tokens
SET used = true
WHERE session_id = $1
AND used = false
`

func (q *Queries) InvalidatePreviousTokens(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, invalidatePreviousTokens, sessionID)
	return err
}

const markQRTokenUsed = `-- name: MarkQRTokenUsed :exec
UPDATE qr_tokens
SET used = true
WHERE id = $1
`

func (q *Queries) MarkQRTokenUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markQRTokenUsed, id)
	return err
}
