// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (course_id, day_of_week, start_time, end_time, venue)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, course_id, day_of_week, start_time, end_time, venue, created_at, updated_at
`

type CreateScheduleParams struct {
	CourseID  pgtype.UUID
	DayOfWeek int32
	StartTime pgtype.Time
	EndTime   pgtype.Time
	Venue     string
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.CourseID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.Venue,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Venue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules
WHERE id = $1
`

func (q *Queries) DeleteSchedule(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSchedule, id)
	return err
}

const getScheduleByID = `-- name: GetScheduleByID :one
SELECT id, course_id, day_of_week, start_time, end_time, venue, created_at, updated_at FROM schedules
WHERE id = $1
`

func (q *Queries) GetScheduleByID(ctx context.Context, id pgtype.UUID) (Schedule, error) {
	row := q.db.QueryRow(ctx, getScheduleByID, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Venue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSchedulesByCourse = `-- name: GetSchedulesByCourse :many
SELECT id, course_id, day_of_week, start_time, end_time, venue, created_at, updated_at FROM schedules
WHERE course_id = $1
ORDER BY day_of_week ASC, start_time ASC
`

func (q *Queries) GetSchedulesByCourse(ctx context.Context, courseID pgtype.UUID) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, getSchedulesByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.Venue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE schedules
SET day_of_week = $2, start_time = $3, end_time = $4, venue = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, course_id, day_of_week, start_time, end_time, venue, created_at, updated_at
`

type UpdateScheduleParams struct {
	ID        pgtype.UUID
	DayOfWeek int32
	StartTime pgtype.Time
	EndTime   pgtype.Time
	Venue     string
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, updateSchedule,
		arg.ID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.Venue,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Venue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
