// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeSession = `-- name: CloseSession :one
UPDATE sessions
SET status = 'closed', closed_at = NOW()
WHERE id = $1
RETURNING id, course_id, created_by, title, week_number, latitude, longitude, radius_meters, qr_rotation_secs, status, started_at, closed_at
`

func (q *Queries) CloseSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, closeSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.CreatedBy,
		&i.Title,
		&i.WeekNumber,
		&i.Latitude,
		&i.Longitude,
		&i.RadiusMeters,
		&i.QrRotationSecs,
		&i.Status,
		&i.StartedAt,
		&i.ClosedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    course_id,
    created_by,
    title,
    week_number,
    latitude,
    longitude,
    radius_meters,
    qr_rotation_secs,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, 'active'
)
RETURNING id, course_id, created_by, title, week_number, latitude, longitude, radius_meters, qr_rotation_secs, status, started_at, closed_at
`

type CreateSessionParams struct {
	CourseID       pgtype.UUID
	CreatedBy      pgtype.UUID
	Title          pgtype.Text
	WeekNumber     int32
	Latitude       float64
	Longitude      float64
	RadiusMeters   float64
	QrRotationSecs int32
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.CourseID,
		arg.CreatedBy,
		arg.Title,
		arg.WeekNumber,
		arg.Latitude,
		arg.Longitude,
		arg.RadiusMeters,
		arg.QrRotationSecs,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.CreatedBy,
		&i.Title,
		&i.WeekNumber,
		&i.Latitude,
		&i.Longitude,
		&i.RadiusMeters,
		&i.QrRotationSecs,
		&i.Status,
		&i.StartedAt,
		&i.ClosedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getActiveSessionByCourse = `-- name: GetActiveSessionByCourse :one
SELECT id, course_id, created_by, title, week_number, latitude, longitude, radius_meters, qr_rotation_secs, status, started_at, closed_at FROM sessions
WHERE course_id = $1 AND status = 'active'
`

func (q *Queries) GetActiveSessionByCourse(ctx context.Context, courseID pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByCourse, courseID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.CreatedBy,
		&i.Title,
		&i.WeekNumber,
		&i.Latitude,
		&i.Longitude,
		&i.RadiusMeters,
		&i.QrRotationSecs,
		&i.Status,
		&i.StartedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, course_id, created_by, title, week_number, latitude, longitude, radius_meters, qr_rotation_secs, status, started_at, closed_at FROM sessions
WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.CreatedBy,
		&i.Title,
		&i.WeekNumber,
		&i.Latitude,
		&i.Longitude,
		&i.RadiusMeters,
		&i.QrRotationSecs,
		&i.Status,
		&i.StartedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getSessionsByCourse = `-- name: GetSessionsByCourse :many
SELECT id, course_id, created_by, title, week_number, latitude, longitude, radius_meters, qr_rotation_secs, status, started_at, closed_at FROM sessions
WHERE course_id = $1
ORDER BY started_at DESC
`

func (q *Queries) GetSessionsByCourse(ctx context.Context, courseID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, getSessionsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.CreatedBy,
			&i.Title,
			&i.WeekNumber,
			&i.Latitude,
			&i.Longitude,
			&i.RadiusMeters,
			&i.QrRotationSecs,
			&i.Status,
			&i.StartedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
