// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password_hash,
    first_name,
    last_name,
    role,
    department
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, email, first_name, last_name, created_at, google_id, avatar_url, role, password_hash, department, matric_number
`

type CreateUserParams struct {
	Email        string
	PasswordHash pgtype.Text
	FirstName    string
	LastName     string
	Role         UserRole
	Department   string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Role,
		arg.Department,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.Role,
		&i.PasswordHash,
		&i.Department,
		&i.MatricNumber,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, first_name, last_name, created_at, google_id, avatar_url, role, password_hash, department, matric_number FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.Role,
		&i.PasswordHash,
		&i.Department,
		&i.MatricNumber,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, first_name, last_name, created_at, google_id, avatar_url, role, password_hash, department, matric_number FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.Role,
		&i.PasswordHash,
		&i.Department,
		&i.MatricNumber,
	)
	return i, err
}

const upsertGoogleUser = `-- name: UpsertGoogleUser :one
INSERT INTO users (
    email,
    google_id,
    first_name,
    last_name,
    avatar_url,
    department,
    matric_number
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (email) DO UPDATE SET
    google_id  = COALESCE(users.google_id, EXCLUDED.google_id),
    first_name = COALESCE(NULLIF(users.first_name, ''), EXCLUDED.first_name),
    last_name  = COALESCE(NULLIF(users.last_name, ''), EXCLUDED.last_name),
    avatar_url = COALESCE(users.avatar_url, EXCLUDED.avatar_url),
    department = COALESCE(NULLIF(EXCLUDED.department, ''), users.department),
    matric_number = COALESCE(EXCLUDED.matric_number, users.matric_number)
RETURNING id, email, first_name, last_name, created_at, google_id, avatar_url, role, password_hash, department, matric_number
`

type UpsertGoogleUserParams struct {
	Email        string
	GoogleID     pgtype.Text
	FirstName    string
	LastName     string
	AvatarUrl    pgtype.Text
	Department   string
	MatricNumber pgtype.Text
}

func (q *Queries) UpsertGoogleUser(ctx context.Context, arg UpsertGoogleUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertGoogleUser,
		arg.Email,
		arg.GoogleID,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
		arg.Department,
		arg.MatricNumber,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.Role,
		&i.PasswordHash,
		&i.Department,
		&i.MatricNumber,
	)
	return i, err
}
